### ISSUE TITLE
Unit test failure - test_promote_license_namespace_feature

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#201] opened 2020-07-15 21:54 UTC
The following test_promote_license_namespace_feature unit test fails:

```
  File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/runner/work/spdx-online-tools/spdx-online-tools/src/app/views.py", line 1378, in promoteNamespaceRequests
    statusCode = utils.createIssue(licenseAuthorName, licenseName, licenseIdentifier, licenseComments, licenseSourceUrls, licenseHeader, licenseOsi, licenseRequestUrl, token, urlType)
  File "/home/runner/work/spdx-online-tools/spdx-online-tools/src/app/utils.py", line 338, in createIssue
    headers = {'Authorization': 'token ' + token}
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by Ugtan** [comment] 2020-07-15 23:28
Hello, @goneall . I ran the test on my local machine and it seems to be working fine. You can refer to the screenshot. Could you please give some info on how to reproduce the error?

![image](https://user-images.githubusercontent.com/32966387/87609695-dedb0d00-c720-11ea-8969-ad9b501c7c1c.png)

**Comment by rtgdk** [comment] 2020-07-16 10:05
It might be related to #142

**Comment by Ugtan** [comment] 2020-07-16 10:47
@goneall Token is nonetype. There is some issue with your GitHub token. Did you specify the `ACCESS_TOKEN` environment variable correctly?

**Comment by goneall** [comment] 2020-07-19 01:44
The `ACCESS_TOKEN` environment variable is set in Github.

![image](https://user-images.githubusercontent.com/378172/87865173-aefd5680-c926-11ea-9f78-8938b9306277.png)

**Comment by nishantc7** [comment] 2021-03-23 20:19
I am failing to reproduce this the error on my machine, has it been fixed?
```
> python manage.py test app.tests.PromoteLicenseNamespaceViewsTestCase.test_promote_license_namespace_feature
Creating test database for alias 'default'...
System check identified some issues:

WARNINGS:
?: (rest_framework.W001) You have specified a default PAGE_SIZE pagination rest_framework setting,without specifying also a DEFAULT_PAGINATION_CLASS.
        HINT: The default for DEFAULT_PAGINATION_CLASS is None. In previous versions this was PageNumberPagination. If you wish to define PAGE_SIZE globally whilst defining pagination_class on a per-view basis you may silence this check.

System check identified 1 issue (0 silenced).
.
----------------------------------------------------------------------
Ran 1 test in 9.322s

OK
Destroying test database for alias 'default'...
```

**Comment by goneall** [comment] 2021-03-24 03:42
@nishantc7 Since you and @Ugtan can't reproduce this, it may be something specific to my environment and not an issue with the online tools

**Comment by rtgdk** [comment] 2021-03-25 17:38
@goneall Did we see this test failed on production?
@nishantc7 Did you setup github and other tokens before running this test?

**Comment by nishantc7** [comment] 2021-03-25 18:00
@rtgdk Yes I did, it does not skip if we export github access token, id and username before testing.

**Comment by rtgdk** [comment] 2021-03-25 18:10
@nishantc7 Then I think this is not an issue. From the error above when the issue was raised, looks like Github token was set to None.

**Comment by BanulaKumarage** [comment] 2023-03-11 16:27
Hi @rtgdk @goneall . I ran this test on my local machine and the test was passed. 

![image](https://user-images.githubusercontent.com/63106638/224495918-ccd7dae8-b2f7-4843-a76b-914c5297cd77.png)

**Comment by rtgdk** [comment] 2023-03-12 05:01
@BanulaKumarage Did you have github setup done? And exported `github access token, id and username before testing` as mentioned above. Or did it work without them?

I think we can close this issue once we confirm this.

**Comment by BanulaKumarage** [comment] 2023-03-12 05:11
@rtgdk yes. I have done the github setup with adding the access token, id and username for env variables.

**Comment by rtgdk** [comment] 2023-03-12 06:19
@BanulaKumarage Thanks for confirming. Let's add a comment on top of the test to have these variables defined for successful execution.

**Closed by rtgdk** 2023-03-12 06:19 UTC
Labels: gsoc, good-first-issue

**Comment by BanulaKumarage** [comment] 2023-03-12 06:40
I will add and make a PR @rtgdk
