### ISSUE TITLE
Error when submitting a license.

### ISSUE THREAD

**Issue by ghost** [spdx/spdx-online-tools#308] opened 2021-05-07 00:14 UTC
Error when submitting a license, now all my progress is gone. oh well.

`Unexpected error, please email the SPDX technical workgroup that the following error has occurred: Traceback (most recent call last): File "/spdx/src/app/views.py", line 168, in submitNewLicense licenseRequest.save() File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save force_update=force_update, update_fields=update_fields) File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 838, in save_base updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields) File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 924, in _save_table result = self._do_insert(cls._base_manager, using, fields, update_pk, raw) File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 963, in _do_insert using=using, raw=raw) File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method return getattr(self.get_queryset(), name)(*args, **kwargs) File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1079, in _insert return query.get_compiler(using=using).execute_sql(return_id) File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql cursor.execute(sql, params) File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute return self.cursor.execute(sql, params) File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__ six.reraise(dj_exc_type, dj_exc_value, traceback) File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute return self.cursor.execute(sql, params) DataError: value too long for type character varying(35)`

**Comment by jlovejoy** [comment] 2023-01-05 16:51
@goneall - has this been addressed otherwise?

**Comment by goneall** [comment] 2023-01-05 18:27
@jlovejoy As far as I know, this is still an issue.  We should validate all field lengths.  Should be a relatively easy task for someone familiar with Django (which I'm not).

**Comment by BassCoder2808** [comment] 2023-03-09 17:53
Hi @goneall I would like to contribute to this issue if it is still open, can you guide me through like what needs to be done to solve this, it would help me a lot

**Comment by goneall** [comment] 2023-03-09 19:25
@BassCoder2808 First step would be to duplicate the problem - ideally with a unit test that would pass once the issue is resolved.  From the stack trace, the problem.

This issue has to do with fields that exceed the maximum length the database allows.  You can probably find the length restrictions in the Model.  Any field used in submit license that has a maximum length in the database should have a check done which returns an error to the user if the length is exceeded.  For the web based UI, you can do validation in JavaScript - which would be the most friendly.  for the API access, you'll need to validate in the View code.

Hope that's enough to get you started.

**Comment by BassCoder2808** [comment] 2023-03-10 03:27
Thanks a lot @goneall for the explanation, I will start with it and will let you know if I am facing any difficulties in it

**Comment by BassCoder2808** [comment] 2023-03-10 18:06
Hi @goneall , I have figured out that we need to change the `forms.py` in the `src/app` directory.
We can do `forms.EmailField(label='Email', initial=self.email, max_length=35, required=False)` as in our model we have a set the max_length to be 35 for the email field. By this we will not have to change the frontend because this will automatically check the length while submission as we are using the same form in the frontend.
Let me know if you fell any changes have to be made to this, or else I will create a PR for the same to solve this

**Comment by goneall** [comment] 2023-03-10 20:44
@BassCoder2808 - Sounds like a better approach than what I was thinking.  Please cod ahead and create a PR.

**Comment by BassCoder2808** [comment] 2023-03-11 03:52
I haave created a pull request now @goneall , please let me know if anything needs to be changed

**Comment by jlovejoy** [comment] 2023-06-21 23:44
@BassCoder2808 @goneall - looks like this had a PR and was merged, can I close issue now? :)

**Comment by goneall** [comment] 2024-01-19 20:00
Resolved with PR #443

**Closed by goneall** 2024-01-19 20:00 UTC
Labels: Submit New License
