### ISSUE TITLE
Some example SPDX files are not working with the SPDX validation tool

### ISSUE THREAD

**Issue by makdataproj** [spdx/spdx-online-tools#338] opened 2022-03-09 17:11 UTC
The online tool https://tools.spdx.org/app/validate/ is getting an error with the example spdx file:
https://raw.githubusercontent.com/spdx/spdx-examples/master/example7/spdx/example7-golang.spdx.json:

**Analysis exception processing SPDX file: string is not a valid SPDX class**

Just curious if this issue is being looked into?

**Comment by goneall** [comment] 2022-03-09 21:51
@makdataproj Thanks for for reporting this issue.  It was not being looked into.

I traced the issue down to a dependent library and created the following issue:

https://github.com/spdx/spdx-java-jackson-store/issues/30

I'll leave this issue open to track updating the dependencies once the issue is resolved.

**Comment by volviq** [comment] 2022-09-21 13:53
@goneall  I tried to fix the example file according to your comment to set up a PR, but that didn't solve the problem:
https://github.com/spdx/spdx-examples/blob/master/example7/spdx/example7-bin.spdx.json
-> replaced as you proposed. Then I get the error: 
"Analysis exception processing SPDX file: Missing SPDX element for ID DocumentRef-golang-dist"
At least it jumps to the next error now.

**Comment by volviq** [comment] 2022-09-21 13:58
Update: I found this issue now:
https://github.com/spdx/spdx-examples/issues/34
So I assume that #338 can be closed and 34 of "examples" needs to be resolved?

**Comment by goneall** [comment] 2022-09-22 06:02
> So I assume that https://github.com/spdx/spdx-online-tools/issues/338 can be closed and 34 of "examples" needs to be resolved?

@volviq I agree

**Comment by rtgdk** [comment] 2022-10-09 08:23
Closing this. Track https://github.com/spdx/spdx-examples/issues/34 for updates

**Closed by rtgdk** 2022-10-09 08:23 UTC
