### ISSUE TITLE
Validate tool unable to handle large SBOMS

### ISSUE THREAD

**Issue by dkruszew** [spdx/spdx-online-tools#317] opened 2021-06-22 15:36 UTC
It appears, to be confirmed, that the SBOM validate tools are unable to handle large SBOMs (>1000 nodes).

![image](https://user-images.githubusercontent.com/54693931/122954641-7800a380-d334-11eb-8a8c-899ee94dff58.png)

A problematic file is attached to this issue. More examples are also available with same error.

[keycloak-13.0.1.zip-too-big.txt](https://github.com/spdx/tools/files/6695626/keycloak-13.0.1.zip-too-big.txt)

**Comment by goneall** [comment] 2021-06-25 01:05
Now that I moved this over, I realize this is a duplicate of #306 

I'll copy over some of the comments and close this issue.

**Closed by goneall** 2021-06-25 01:05 UTC

**Comment by goneall** [comment] 2021-07-13 00:44
I did a some experimentation and found the issue is really https://github.com/spdx/Spdx-Java-Library/issues/40

If I comment out the check for removing in-use SPDX ID's, the time it take to verify keycloak-13.0.1.zip-too-big goes from 1:42 down to less than 6 seconds on my machine - a 16X improvement in performance.
