### ISSUE TITLE
"Submit license" form apparently only allows 25 characters for suggested short identifier

### ISSUE THREAD

**Issue by richardfontana** [spdx/spdx-online-tools#512] opened 2023-10-19 21:38 UTC
While one might reasonably think that, in coming up with a short identifier for a license, "25 characters ought to be enough for anybody", the growing complexity of the SPDX license list (including relationships between identifiers) probably makes this limitation inadequate. I am trying to submit a license that is a variant of `FSFAP` but without the final sentence containing a simple warranty disclaimer. So a natural choice of short identifier is `FSFAP-no-warranty-disclaimer` but this exceeds the apparent 25 character limit.

**Comment by goneall** [comment] 2023-10-19 22:49
@richardfontana - should we have a limit on the length of the ID's?  If so, what would be reasonable?

**Comment by richardfontana** [comment] 2023-10-20 01:16
@goneall my thought was perhaps double the existing limit?

**Comment by richardfontana** [comment] 2023-10-28 13:31
I was again hit by this limitation when attempting to submit a new license. I wanted to suggest the identifier `BSD-3-Clause-Intel-variant` but the form would only give space for `BSD-3-Clause-Intel-varian`.

**Comment by goneall** [comment] 2023-10-30 16:53
Due to the demands from the SPDX 3.0 release, I probably won't get to a fix in the near term.  Hoping to find a volunteer in the community to provide a pull request.

**Comment by Ash-KODES** [comment] 2023-11-27 13:15
Can I work on this ? @goneall

**Comment by goneall** [comment] 2023-11-27 14:36
@Ash-KODES - that would be great - thanks!

**Comment by goneall** [comment] 2023-12-18 00:10
@Ash-KODES It would be great to get in a pull request for this soon - I'm planning on doing a release this week.

Let me know if you're able to take this on - otherwise I'll take a stab at it.

cc: @rtgdk

**Comment by Ash-KODES** [comment] 2023-12-18 05:27
I will make a PR for this  today

**Comment by goneall** [comment] 2023-12-27 18:19
@Ash-KODES - Just checking in on the PR - let me know if you think you'll be able to get the PR done in the next day or so

**Comment by BassCoder2808** [comment] 2024-01-02 17:29
Hi @goneall, If the issue is still open I would like to contribute to it, I will create the PR for the same and you can review it and we can move forward with it

**Comment by BassCoder2808** [comment] 2024-01-03 17:25
We can close this issue now @goneall

**Closed** 2024-01-03 19:32 UTC
Labels: enhancement, good-first-issue
